version: '3'
services:
  rss3hub:
    image: nyawork/rss3go-hub
    container_name: rss3go-hub
    ports:
      - 127.0.0.1:8080:8080
    restart: always
    volumes:
      - ./config.yml:/config.yml:ro
